### PR TITLE
Parallel Decompression Support

### PR DESCRIPTION
**Pull request by clee-ai**

### CODE REVIEW

**Comment by clee-ai** [comment]
@tmontaigu Hey, I'm trying to implement a parallel decompression API for C/C++. To do this, I made an enum between the two types of decompressors:

```rust
pub enum Lazrs_Decompressor {
    decompressor(laz::LasZipDecompressor<'static, CSource<'static>>),
    par_decompressor(laz::ParLasZipDecompressor<CSource<'static>>),
}
```

And have the `Lazrs_LasZipDecompressor` struct just take an enum instance:

```rust
pub struct Lazrs_LasZipDecompressor {
    decompressor: Lazrs_Decompressor,
}
```

I'm running into issues with using this enum with the pointers, and I'm not sure how to solve it. For example:

```rust
pub unsafe extern "C" fn lazrs_decompressor_decompress_one(
    decompressor: *mut Lazrs_LasZipDecompressor,
    out: *mut u8,
    len: libc::size_t,
) -> Lazrs_Result {
    debug_assert!(!decompressor.is_null());
    debug_assert!(!out.is_null());
    let buf = std::slice::from_raw_parts_mut(out, len);
    match (*decompressor).decompressor {
        Lazrs_Decompressor::par_decompressor (_d) => { Lazrs_Result::LAZRS_OTHER }
        Lazrs_Decompressor::decompressor (d) => { d.decompress_one(buf).into() }
    }
}
```

This function throws the error ```cannot move out of `decompressor.decompressor.0` which is behind a raw pointer```. I was wondering if you have any ideas. I'm not very good in rust :)

**Comment by tmontaigu** [comment]
When you do `match (*decompressor).decompressor`, by default Rust will `move` the value, but you can't move values that are behind pointers.

You have to tell rust that you want to `borrow` the values and you have two ways two do that in this case: 
```Rust
match &(*decompressor).decompressor {
/// ...
}
```
or (which i find more obvious to understand when reading)
```Rust
match (*decompressor).decompressor {
    Lazrs_Decompressor::par_decompressor (ref mut d) => { d.decompress_many(buf).into() }
    Lazrs_Decompressor::decompressor (ref mut d) => { d.decompress_many(buf).into() }
}
```

**Comment by clee-ai** [comment]
Thanks for the feedback!

I did try the first suggestion before (`match &(*decompressor).decompressor`), it gives the following result:

```
error[E0596]: cannot borrow `*d` as mutable, as it is behind a `&` reference
   --> src\lib.rs:242:55
    |
242 |         Lazrs_Decompressor::par_decompressor (d) => { d.decompress_many(buf).into() }
    |                                                       ^ `d` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

The second suggestion did the charm though! I just had to mark CSource and CFile as public (not crate-private) and it seemed to compile okay.

**Comment by tmontaigu** [comment]
The first solution should have been `&mut(*decompressor)....`

**Comment by clee-ai** [comment]
Okay, should be ready now. In my tests, parallel gets about 4-6x speedup (23s vs 136s).

**Comment by clee-ai** [comment]
I also added support for reading directly from a filename, since libc::fseek doesn't allow for anything over an int32 on windows.

**Comment by tmontaigu** [comment]
So a few general things about the 'API design':

What I would prefer is that each decompressor from lazrs has its own equivalent in the C API, that is:
- `laz::LasZipDecompressor` would be `Lazrs_LasZipDecompressor`
- `laz::ParLasZipDecompressor` would be `Lazrs_ParLasZipDecompressor`

And then we could have a 3rd type `Lazrs_Decompressor` which can be either a `laz::LasZipDecompressor` or `laz::ParLasZipDecompressor` like you did.

---

I'm not a fan of accepting file names as parameters, what I envisionned is to use callbacks for seek and read in the form of function pointers. 
These callbacks would be given by the C or C++ user when creating the decompressor.

So that as long as we have seek and read call backs we can decompress from any kind of custom source from the user.
And also, the C++ API could provide default callbacks for of the  C++ standard streams.

But we can keep the filename source for now, it may be removed later.

**Comment by clee-ai** [comment]
I'm a bit confused by your first point, could you detail more specifically what you want me to change?

**Comment by tmontaigu** [comment]
You changed 
```Rust
pub struct Lazrs_LasZipDecompressor {
    decompressor: laz::LasZipDecompressor<'static, CSource<'static>>,
}
```

into
```Rust
pub enum Lazrs_Decompressor {
    decompressor(laz::LasZipDecompressor<'static, CSource<'static>>),
    par_decompressor(laz::ParLasZipDecompressor<CSource<'static>>),
}

pub struct Lazrs_LasZipDecompressor {
    decompressor: Lazrs_Decompressor,
}
```


what I would prefer is 
```Rust

pub struct Lazrs_LasZipDecompressor {
    decompressor: laz::LasZipDecompressor<'static, CSource<'static>>,
}

pub struct Lazrs_ParLasZipDecompressor {
    decompressor: laz::ParLasZipDecompressor<'static, CSource<'static>>,
}

pub enum Lazrs_Decompressor {
    decompressor(laz::LasZipDecompressor<'static, CSource<'static>>),
    par_decompressor(laz::ParLasZipDecompressor<CSource<'static>>),
}

// Each Lazrs_* thing would have its functions
```

If you don't want to do the bindings for `Lazrs_ParLasZipDecompressor ` I can do them, but a least I want  your PR to have a
`Lazrs_LasZipDecompressor` C type that can only be a non parallel laz decompressor and `Lazrs_Decompressor ` that can be both.

 I hope its clearer

**Comment by tmontaigu** [comment]
Realized it would involve more code duplication that I initially thought so i'm merging this for now

**Pull request merged**
